title: Progetto ItaCa
# # email: your-email@example.com
# description: |
#   _Blind monks examining an elephant_
#   Hanabusa Itchō
url: "https://progetto-itaca.github.io"
baseurl: "/"

favicon: favicon.ico

markdown: kramdown

# exclude: [vendor, BACKUP, script, Gemfile, Gemfile.lock, .gitignore]

