title: Progetto ItaCa
url: "https://progetto-itaca.github.io"
baseurl: "/"

favicon: favicon.ico

markdown: kramdown

plugins:
  - "jekyll/scholar"

scholar:
  style: apa # NOTE: this is just the default
